# Generated by Django 5.0.7 on 2024-07-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_website_user_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_user',
            old_name='iamge',
            new_name='image',
        ),
    ]
