# Generated by Django 5.0.7 on 2024-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_website_user_last_login_alter_website_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mystudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='website_user',
        ),
    ]
